server:
  port: 8100
##########fastdfs基本配置###开始###################### 
fdfs:
  #获取文件超时时间
  soTimeout: 15001
  #连接超时时间
  connectTimeout: 16001 
  #缩列图大小定义
  thumbImage:
    width: 150
    height: 150
  #前端获取url
  webServerUrl: http://192.168.93.132:8888/
  #防盗链key
  secret_key: FastDFS1234567890
  #fastdfs服务器地址，配置的是集群版时，即添加多个地址
  trackerList:
#    - 40.125.175.235:22122
#    - 120.78.151.45:22122
    - 192.168.93.132:22122
#    - 192.168.174.47:22122
#    - 192.168.174.48:22122
##########fastdfs基本配置###结束######################